(define (problem pnp)
	(:domain pnp)

(:objects
    	arm - bot
    	syrup - object
    	can - object
    	pos1 pos2 pos0 pos3 pos4 pos5 pos6 pos7 - position
	)

	(:init
	(at arm pos0 )
	(located_at syrup pos1)
	(located_at can pos2)
	(empty arm)
	(free pos6)
	(free pos7)
	(free pos5)
	(free pos4)
	(free pos3)
	(path pos0 pos1 )
	(path pos0 pos2 )
	(path pos0 pos3 )
	(path pos0 pos4 )
	(path pos0 pos5 )
	(path pos0 pos6 )
	(path pos0 pos7 )
	(path pos1 pos2 )
	(path pos1 pos3 )
	(path pos1 pos4 )
	(path pos1 pos5 )
	(path pos1 pos6 )
	(path pos1 pos7 )
	(path pos2 pos1 )
	(path pos2 pos3 )
	(path pos2 pos4 )
	(path pos2 pos5 )
	(path pos2 pos6 )
	(path pos2 pos7 )
	(path pos3 pos1 )
	(path pos3 pos2 )
	(path pos3 pos4 )
	(path pos3 pos5 )
	(path pos3 pos6 )
	(path pos3 pos7 )
	(path pos4 pos1 )
	(path pos4 pos2 )
	(path pos4 pos3 )
	(path pos4 pos5 )
	(path pos4 pos6 )
	(path pos4 pos7 )
	(path pos5 pos1 )
	(path pos5 pos2 )
	(path pos5 pos3 )
	(path pos5 pos4 )
	(path pos5 pos6 )
	(path pos5 pos7 )
	(path pos6 pos1 )
	(path pos6 pos2 )
	(path pos6 pos3 )
	(path pos6 pos4 )
	(path pos6 pos5 )
	(path pos6 pos7 )
	(path pos7 pos1 )
	(path pos7 pos2 )
	(path pos7 pos3 )
	(path pos7 pos4 )
	(path pos7 pos5 )
	(path pos7 pos6 )
	(reachable arm pos1 )
	(reachable arm pos2 )
	(reachable arm pos3 )
	(reachable arm pos4 )
	(reachable arm pos5 )
	(reachable arm pos6 )
	(reachable arm pos7 )
)
(:goal 
	(and (located_at can pos7))

)
)
